blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Ali-Mohammed/openRadius/wiki
    about: Check our documentation before opening an issue.
  - name: Discussions
    url: https://github.com/Ali-Mohammed/openRadius/discussions
    about: Ask questions and discuss ideas in GitHub Discussions.
